title: O.R.I. Containment District: Outpost-60
description: whar
theme: just-the-docs

url: https://mattgamer6660.github.io/containmentdistrict/

aux_links_new_tab: true

aux_links:
  "Primary Operations.":
    - "https://www.roblox.com/groups/7595770/Orion-Research-Initiative#!/about"
  "Containment District.":
    - "https://www.roblox.com/groups/8664655/Energy-Corp-Response-Team#!/about"
  "Administration Council.":
    - "https://www.roblox.com/groups/9777413/The-Foundation-SCP-F#!/about"
